### PR TITLE
Development

### PR DESCRIPTION
**Pull request by markonikovic**
New York Times Clone Page:

-We recreated the web page (https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0).

-We use CSS-grid, flex-box and floats to position the elements on the web page.
-We embedded images, a video, and an iframe.

-We used semantic HTML tags as much as we could.

-We used aside tag for the 'Editor's pick' section and positioned it to the rightmost side.

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey team, 👋

## Good job on this project! 👍

- Good Readme template
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to activate your repo in Stickler. I cannot see your linters working :smile: !!

- Improve your Readme file. You are using a great template. Now add some more information about the project: the purpose, how you did and why.

- The NYT logo should be centered and it should be a link, like the original page.

- Please implement all the hover effects the original page has: on the social media links, the links on the text, the aside links, the links on the picture div, and the footer links.
It is possible that the next reviewer will make you change some other elements, o
- The navbar should be fixed and visible when you scroll down. Please make this change.

- Work on your general layout. The page is not behaving like the original one. 
   - For instance, you have a horizontal scroll bar that shouldn't be there (check the header).
   - Your main content is not centered.
   - The div picture section is too wide and it should be centered, like the rest of the content.
    Your page:
Screenshot from 2020-02-27 22-06-35

    Original page:
Screenshot from 2020-02-27 22-06-46

   - Your footer is too wide. See screenshot:
Screenshot from 2020-02-27 22-09-29

   Original page:
Screenshot from 2020-02-27 22-09-35

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by majovanilla** [comment]
Hey Team 👋

You are almost there!!

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- You are still missing the hover effects required in the previous review. Please address them. This is related to this Odin requirement: 
Screenshot from 2020-02-28 12-45-31

- You are using an image in the Theory of Inflation. I apologize for not have noticed that in the first review. Using an image here is the opposite of the purpose of the project!! You need to follow the same structure as the original page and use an image and position the paragraph with float, flex or grid. That will make you have a deeper understanding of positioning and also improve the quality of your work. :medal_sports: 
Screenshot from 2020-02-28 12-45-09

- Your aside element (editor's picks) is still not looking quite like the original one. Check it out.
Your page:
Screenshot from 2020-02-28 12-47-07

Original page:
Screenshot from 2020-02-28 12-47-02

- The last section is a little wider than the original page. Please make it look closer to the original version. Check the font size, the space between elements... every detail counts!


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by SofiBretz** [comment]
Code under review by SofiBretz. Thanks!✨

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but you need to fix the issues below before moving on ⬇️

- [ ]As the last TSE explain it before: "Using an image here is the opposite of the purpose of the project!...", Consider that on 'The Theory of Inflation' section, **the image can not be a Screenshot** You can do it! is part of the exercise 💪 



- [ ] As the last TSE explains: "...Your aside element (editor's picks) is still not looking quite like the original one...", the images and the text are bigger than the original, the idea of this exercise is to learn how to design the page as the original one. 





- [ ] Consider follow the original page on the 'More in Space and Astronomy' and 'Most Popular' section, for example, the icons are bigger than the original page, titles font size is bigger, etc. Consider building the page as the original.





- [ ] Missing icons on the right side on the footer, and follow the design (text, space, etc) as the original page.





- [ ] Consider respect the space on the bottom on the footer and follow the same font size as the original page.



- [ ] Description has to occupy the same size as the image, please look at the original:





- [ ] Pull Request has a meaningful title and a short description, [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/
) you can learn about it. 

[OPTIONAL]

- [ ] Consider adding a screenshot of your project and the demo link in your readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by uryelah** [comment]
Hello **Salvo Illuminato** & **Marko Nikovic**, I'm Sarah, your reviewer for this PR 👩‍🚀 

You guys did an amazing job going through all the code reviews and fixing that one last bug 🥇 

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
